// hairColor options: purple, orange, blue, yellow, green, brown, black, white
// eyeColor options: orange, blue, green, grey, black, white
// hobby options: pickling, car making

module.exports = [
    {
        id: 4,
        firstName: '',
        lastName: '',
        gender: '',
        hairColor: '',
        eyeColor: '',
        hobby: '',
        birthDay: 7,
        birthMonth: 22,
        birthYear: 1979
    },
    {
        id: 5,
       firstName: '',
        lastName: '',
        gender: '',
        hairColor: '',
        eyeColor: '',
        hobby: '',
        birthDay: 8,
        birthMonth: 22,
        birthYear: 1994
    },
    {
        id: 6,
       firstName: '',
        lastName: '',
        gender: '',
        hairColor: '',
        eyeColor: '',
        hobby: '',
        birthDay: 1,
        birthMonth: 2,
        birthYear: 1920
    },
    {
        id: 7,
       firstName: '',
        lastName: '',
        gender: '',
        hairColor: '',
        eyeColor: '',
        hobby: '',
        birthDay: 4,
        birthMonth: 20,
        birthYear: 1962
    },
    {
        id: 8,
       firstName: '',
        lastName: '',
        gender: '',
        hairColor: '',
        eyeColor: '',
        hobby: '',
        birthDay: 7,
        birthMonth: 14,
        birthYear: 2015
    },
    {
        id: 9,
       firstName: '',
        lastName: '',
        gender: '',
        hairColor: '',
        eyeColor: '',
        hobby: '',
        birthDay: 5,
        birthMonth: 1,
        birthYear: 1990
    },
    {
        id: 10,
       firstName: '',
        lastName: '',
        gender: '',
        hairColor: '',
        eyeColor: '',
        hobby: '',
        birthDay: 6,
        birthMonth: 7,
        birthYear: 1789
    },
    {
        id: 11,
       firstName: '',
        lastName: '',
        gender: '',
        hairColor: '',
        eyeColor: '',
        hobby: '',
        birthDay: 3,
        birthMonth: 30,
        birthYear: 1930
    },
    {
        id: 12,
       firstName: '',
        lastName: '',
        gender: '',
        hairColor: '',
        eyeColor: '',
        hobby: '',
        birthDay: 6,
        birthMonth: 8,
        birthYear: 1912
    },
    {
        id: 13,
       firstName: '',
        lastName: '',
        gender: '',
        hairColor: '',
        eyeColor: '',
        hobby: '',
        birthDay: 2,
        birthMonth: 11,
        birthYear: 1980
    },
    {
        id: 14,
       firstName: '',
        lastName: '',
        gender: '',
        hairColor: '',
        eyeColor: '',
        hobby: '',
        birthDay: 4,
        birthMonth: 7,
        birthYear: 1970
    },
    {
        id: 15,
       firstName: '',
        lastName: '',
        gender: '',
        hairColor: '',
        eyeColor: '',
        hobby: '',
        birthDay: 3,
        birthMonth: 5,
        birthYear: 1912
    },
    {
        id: 16,
       firstName: '',
        lastName: '',
        gender: '',
        hairColor: '',
        eyeColor: '',
        hobby: '',
        birthDay: 8,
        birthMonth: 9,
        birthYear: 1910
    },
    {
        id: 17,
       firstName: '',
        lastName: '',
        gender: '',
        hairColor: '',
        eyeColor: '',
        hobby: '',
        birthDay: 12,
        birthMonth: 25,
        birthYear: 1900
    },
    {
        id: 18,
       firstName: '',
        lastName: '',
        gender: '',
        hairColor: '',
        eyeColor: '',
        hobby: '',
        birthDay: 10,
        birthMonth: 31,
        birthYear: 1969
    },
    {
        id: 19,
       firstName: '',
        lastName: '',
        gender: '',
        hairColor: '',
        eyeColor: '',
        hobby: '',
        birthDay: 11,
        birthMonth: 4,
        birthYear: 1900
    },
    {
        id: 20,
       firstName: '',
        lastName: '',
        gender: '',
        hairColor: '',
        eyeColor: '',
        hobby: '',
        birthDay: 3,
        birthMonth: 23,
        birthYear: 1940
    },
    {
        id: 21,
       firstName: '',
        lastName: '',
        gender: '',
        hairColor: '',
        eyeColor: '',
        hobby: '',
        birthDay: 5,
        birthMonth: 9,
        birthYear: 1931
    },
    {
        id: 22,
       firstName: '',
        lastName: '',
        gender: '',
        hairColor: '',
        eyeColor: '',
        hobby: '',
        birthDay: 7,
        birthMonth: 29,
        birthYear: 1945
    },
    {
        id: 23,
       firstName: '',
        lastName: '',
        gender: '',
        hairColor: '',
        eyeColor: '',
        hobby: '',
        birthDay: 3,
        birthMonth: 6,
        birthYear: 1969
    },
    {
        id: 24,
       firstName: '',
        lastName: '',
        gender: '',
        hairColor: '',
        eyeColor: '',
        hobby: '',
        birthDay: 4,
        birthMonth: 25,
        birthYear: 1972
    },
    {
        id: 25,
       firstName: '',
        lastName: '',
        gender: '',
        hairColor: '',
        eyeColor: '',
        hobby: '',
        birthDay: 12,
        birthMonth: 12,
        birthYear: 1912
    },
    {
        id: 26,
       firstName: '',
        lastName: '',
        gender: '',
        hairColor: '',
        eyeColor: '',
        hobby: '',
        birthDay: 11,
        birthMonth: 22,
        birthYear: 1933
    },
    {
        id: 27,
       firstName: '',
        lastName: '',
        gender: '',
        hairColor: '',
        eyeColor: '',
        hobby: '',
        birthDay: 5,
        birthMonth: 23,
        birthYear: 1550
    }
];