// hairColor options: purple, orange, blue, yellow, green, brown, black, white
// eyeColor options: orange, blue, green, grey, black, white
// hobby options: pickling, synergy, success, help-desk, singing, apple picking, powerpoint, 

module.exports = [
    {
        id: 4,
        firstName: 'Bran',
        lastName: 'Rosenboim',
        gender: 'male',
        img: "https://robohash.org/sitperferendisomnis.png?size=50x50&set=set1",
        hairColor: 'orange',
        eyeColor: 'blue',
        hobby: 'pickling',
        birthDay: 7,
        birthMonth: 22,
        birthYear: 1979
    },
    {
        id: 5,
        firstName: 'Gabriell',
        lastName: 'Dulany',
        gender: 'female',
        img: "https://robohash.org/omnisnumquamdignissimos.png?size=50x50&set=set1",
        hairColor: 'blue',
        eyeColor: 'white',
        hobby: 'singing',
        birthDay: 8,
        birthMonth: 22,
        birthYear: 1994
    },
    {
        id: 6,
        firstName: 'Lowrance',
        lastName: 'Sagar',
        gender: 'male',
        img: "https://robohash.org/velitnecessitatibusiste.png?size=50x50&set=set1",
        hairColor: 'orange',
        eyeColor: 'blue',
        hobby: 'apple picking',
        birthDay: 1,
        birthMonth: 2,
        birthYear: 1920
    },
    {
        id: 7,
        firstName: 'Damian',
        lastName: 'Ferrick',
        gender: 'male',
        img: "https://robohash.org/eumrerumerror.png?size=50x50&set=set1",
        hairColor: 'green',
        eyeColor: 'black',
        hobby: 'apple picking',
        birthDay: 4,
        birthMonth: 20,
        birthYear: 1962
    },
    {
        id: 8,
        firstName: 'Duncan',
        lastName: 'Virgin',
        gender: 'male',
        img: "https://robohash.org/ipsamoditautem.png?size=50x50&set=set1",
        hairColor: 'purple',
        eyeColor: 'black',
        hobby: 'powerpoint',
        birthDay: 7,
        birthMonth: 14,
        birthYear: 2015
    },
    {
        id: 9,
        firstName: 'Odessa',
        lastName: 'Hardiman',
        gender: 'female',
        img: "https://robohash.org/consequaturquisquamasperiores.png?size=50x50&set=set1",
        hairColor: 'purple',
        eyeColor: 'green',
        hobby: 'singing',
        birthDay: 5,
        birthMonth: 1,
        birthYear: 1990
    },
    {
        id: 10,
        firstName: 'Mortie',
        lastName: 'Ubsdall',
        gender: 'male',
        img: "https://robohash.org/quietpariatur.png?size=50x50&set=set1",
        hairColor: 'yellow',
        eyeColor: 'blue',
        hobby: 'singing',
        birthDay: 6,
        birthMonth: 7,
        birthYear: 1789
    },
    {
        id: 11,
        firstName: 'Abbie',
        lastName: 'Heffernon',
        gender: 'male',
        img: "https://robohash.org/accusantiumaddolor.png?size=50x50&set=set1",
        hairColor: 'orange',
        eyeColor: 'grey',
        hobby: 'success',
        birthDay: 3,
        birthMonth: 30,
        birthYear: 1930
    },
    {
        id: 12,
        firstName: 'Teodoro',
        lastName: 'Corney',
        gender: 'male',
        img: "https://robohash.org/doloribusutlaudantium.png?size=50x50&set=set1",
        hairColor: 'black',
        eyeColor: 'blue',
        hobby: 'success',
        birthDay: 6,
        birthMonth: 8,
        birthYear: 1912
    },
    {
        id: 13,
        firstName: 'Trista',
        lastName: 'Olman',
        gender: 'female',
        img: "https://robohash.org/voluptatemnostrumofficia.png?size=50x50&set=set1",
        hairColor: 'orange',
        eyeColor: 'white',
        hobby: 'pickling',
        birthDay: 2,
        birthMonth: 11,
        birthYear: 1980
    },
    {
        id: 14,
        firstName: 'Aluino',
        lastName: 'Mallison',
        gender: 'male',
        img:  "https://robohash.org/praesentiumaliquidsoluta.png?size=50x50&set=set1",
        hairColor: 'orange',
        eyeColor: 'grey',
        hobby: 'singing',
        birthDay: 4,
        birthMonth: 7,
        birthYear: 1970
    },
    {
        id: 15,
        firstName: 'Sallyann',
        lastName: 'Esby',
        gender: 'female',
        img: "https://robohash.org/voluptasquifugit.png?size=50x50&set=set1",
        hairColor: 'yellow',
        eyeColor: 'grey',
        hobby: 'synergy',
        birthDay: 3,
        birthMonth: 5,
        birthYear: 1912
    },
    {
        id: 16,
        firstName: 'Jeffrey',
        lastName: 'Guerreiro',
        gender: 'male',
        img: "https://robohash.org/sitmolestiaeautem.png?size=50x50&set=set1",
        hairColor: 'yellow',
        eyeColor: 'grey',
        hobby: 'pickling',
        birthDay: 8,
        birthMonth: 9,
        birthYear: 1910
    },
    {
        id: 17,
        firstName: 'Blanca',
        lastName: 'Daughtrey',
        gender: 'female',
        img: "https://robohash.org/itaqueminusqui.png?size=50x50&set=set1",
        hairColor: 'black',
        eyeColor: 'black',
        hobby: 'synergy',
        birthDay: 12,
        birthMonth: 25,
        birthYear: 1900
    },
    {
        id: 18,
        firstName: 'Karl',
        lastName: 'Davitt',
        gender: 'male',
        img: "https://robohash.org/natusaperiamconsectetur.png?size=50x50&set=set1",
        hairColor: 'blue',
        eyeColor: 'green',
        hobby: 'help-desk',
        birthDay: 10,
        birthMonth: 31,
        birthYear: 1969
    },
    {
        id: 19,
        firstName: 'Binny',
        lastName: 'Vela',
        gender: 'male',
        img: "https://robohash.org/illoearumquaerat.png?size=50x50&set=set1",
        hairColor: 'black',
        eyeColor: 'blue',
        hobby: 'help-desk',
        birthDay: 11,
        birthMonth: 4,
        birthYear: 1900
    },
    {
        id: 20,
        firstName: 'Ephrem',
        lastName: 'Kruschov',
        gender: 'male',
        img: "https://robohash.org/occaecatiutdoloribus.png?size=50x50&set=set1",
        hairColor: 'yellow',
        eyeColor: 'green',
        hobby: 'singing',
        birthDay: 3,
        birthMonth: 23,
        birthYear: 1940
    },
    {
        id: 21,
        firstName: 'Victoria',
        lastName: 'Fryer',
        gender: 'female',
        img: "https://robohash.org/consequaturdolortempore.png?size=50x50&set=set1",
        hairColor: 'purple',
        eyeColor: 'white',
        hobby: 'apple picking',
        birthDay: 5,
        birthMonth: 9,
        birthYear: 1931
    },
    {
        id: 22,
        firstName: 'Tremaine',
        lastName: 'Barkley',
        gender: 'male',
        img: "https://robohash.org/ametetqui.png?size=50x50&set=set1",
        hairColor: 'brown',
        eyeColor: 'green',
        hobby: 'powerpoint',
        birthDay: 7,
        birthMonth: 29,
        birthYear: 1945
    },
    {
        id: 23,
        firstName: 'Sibelle',
        lastName: 'Hampstead',
        gender: 'female',
        img: "https://robohash.org/maioresinnostrum.png?size=50x50&set=set1",
        hairColor: 'white',
        eyeColor: 'white',
        hobby: 'apple picking',
        birthDay: 3,
        birthMonth: 6,
        birthYear: 1969
    },
    {
        id: 24,
        firstName: 'Dory',
        lastName: 'Bamlett',
        gender: 'male',
        img: "https://robohash.org/temporaeaquis.png?size=50x50&set=set1",
        hairColor: 'brown',
        eyeColor: 'grey',
        hobby: 'success',
        birthDay: 4,
        birthMonth: 25,
        birthYear: 1972
    },
    {
        id: 25,
        firstName: 'Shaw',
        lastName: 'Tollerfield',
        gender: 'male',
        img: "https://robohash.org/quosveritatisquas.png?size=50x50&set=set1",
        hairColor: 'green',
        eyeColor: 'white',
        hobby: 'powerpoint',
        birthDay: 12,
        birthMonth: 12,
        birthYear: 1912
    },
    {
        id: 26,
        firstName: 'Nanci',
        lastName: 'Ludmann',
        gender: 'female',
        img: "https://robohash.org/voluptatemenimrerum.png?size=50x50&set=set1",
        hairColor: 'white',
        eyeColor: 'green',
        hobby: 'success',
        birthDay: 11,
        birthMonth: 22,
        birthYear: 1933
    },
    {
        id: 27,
        firstName: 'Andie',
        lastName: 'Enoksson',
        gender: 'male',
        img: "https://robohash.org/atfacereexercitationem.png?size=50x50&set=set1",
        hairColor: 'green',
        eyeColor: 'blue',
        hobby: 'synergy',
        birthDay: 5,
        birthMonth: 23,
        birthYear: 1550
    }
];